name: Run Zoner and Push to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ensure public directory exists
        run: mkdir -p public

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Build Blog with Zoner
        run: |
          chmod +x ./zoner
          ./zoner -i blog -o public

      - name: Deploy to Nekoweb
        uses: indiefellas/deploy2nekoweb@main  # Changed from @v1 to @main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_TOKEN }} # Updated configuration names
          directory: './public'
